"use client";

import { useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";
import { LineMaterial } from "three/addons/lines/LineMaterial.js";
import { LineSegments2 } from "three/addons/lines/LineSegments2.js";
import { LineSegmentsGeometry } from "three/addons/lines/LineSegmentsGeometry.js";
import type { Building } from "./types";
import { createIsometricCamera, fitIsometricCamera } from "./isometricCamera";
import { createRoofPvArray } from "./roofPvArray";

type Point3=[number,number,number];
type SelectableGroup=THREE.Group&{userData:{buildingId:string;wall:THREE.MeshStandardMaterial;glass:THREE.MeshStandardMaterial;line:LineMaterial;pv:THREE.Group}};

function addQuad(positions:number[],indices:number[],a:Point3,b:Point3,c:Point3,d:Point3){const start=positions.length/3;positions.push(...a,...b,...c,...d);indices.push(start,start+1,start+2,start,start+2,start+3)}
function mesh(positions:number[],indices:number[],material:THREE.Material){const geometry=new THREE.BufferGeometry();geometry.setAttribute("position",new THREE.Float32BufferAttribute(positions,3));geometry.setIndex(indices);geometry.computeVertexNormals();return new THREE.Mesh(geometry,material)}
function setBuildingId(root:THREE.Object3D,id:string){root.traverse(item=>{item.userData.buildingId=id})}

function buildingModel(id:string,raw:Point3[],building:Building){
  const minZ=Math.min(...raw.map(v=>v[2])),bottom=raw.filter(v=>Math.abs(v[2]-minZ)<.01),clean=bottom.filter((v,i)=>i===0||Math.hypot(v[0]-bottom[i-1][0],v[1]-bottom[i-1][1])>.001);
  if(clean.length>2&&Math.hypot(clean[0][0]-clean.at(-1)![0],clean[0][1]-clean.at(-1)![1])<.001)clean.pop();if(clean.length<3)return null;
  const xy=clean.map(v=>new THREE.Vector2(v[0],v[1])),signedArea=THREE.ShapeUtils.area(xy);if(Math.abs(signedArea)<1)return null;
  const height=Math.max(building.height||Math.max(...raw.map(v=>v[2]))-minZ,3),floors=Math.max(1,Math.round(building.floors||4)),group=new THREE.Group() as SelectableGroup;
  const wall=new THREE.MeshStandardMaterial({color:0xd7dfdc,roughness:.82,metalness:.02,side:THREE.DoubleSide}),glass=new THREE.MeshStandardMaterial({color:0x789097,roughness:.28,metalness:.08,side:THREE.DoubleSide}),line=new LineMaterial({color:0x738b84,linewidth:1.15,transparent:true,opacity:.62,worldUnits:false});group.name=id;
  const shape=new THREE.Shape(xy),base=new THREE.Mesh(new THREE.ShapeGeometry(shape),wall),roof=new THREE.Mesh(new THREE.ShapeGeometry(shape),wall),pv=createRoofPvArray(xy,minZ+height);base.position.z=minZ;roof.position.z=minZ+height;pv.visible=false;group.userData={buildingId:id,wall,glass,line,pv};group.add(base,roof,pv);
  const walls:number[]=[],wallIndices:number[]=[],windows:number[]=[],windowIndices:number[]=[],floorHeight=height/floors,windowHeight=floorHeight*.5,coverage=.6;
  for(let i=0;i<xy.length;i++){const a=xy[i],b=xy[(i+1)%xy.length],dx=b.x-a.x,dy=b.y-a.y,length=Math.hypot(dx,dy);if(length<.5)continue;const ux=dx/length,uy=dy/length,modules=Math.max(1,Math.min(24,Math.floor(length/3.2))),desired=length*coverage/modules,gap=Math.max(.08,(length-desired*modules)/(modules+1)),windowWidth=Math.max(.1,(length-gap*(modules+1))/modules),outward=(signedArea>=0?-1:1)*.025;const point=(distance:number,z:number,offset=0):Point3=>[a.x+ux*distance-uy*offset,a.y+uy*distance+ux*offset,minZ+z];
    for(let floor=0;floor<floors;floor++){const z0=floor*floorHeight,z1=(floor+1)*floorHeight,wb=z0+floorHeight*.25,wt=Math.min(z1-.12,wb+windowHeight);addQuad(walls,wallIndices,point(0,z0),point(length,z0),point(length,wb),point(0,wb));addQuad(walls,wallIndices,point(0,wt),point(length,wt),point(length,z1),point(0,z1));let cursor=0;for(let module=0;module<modules;module++){const start=gap+module*(windowWidth+gap),end=Math.min(length-gap,start+windowWidth);if(start>cursor)addQuad(walls,wallIndices,point(cursor,wb),point(start,wb),point(start,wt),point(cursor,wt));addQuad(windows,windowIndices,point(start,wb,outward),point(end,wb,outward),point(end,wt,outward),point(start,wt,outward));cursor=end}if(cursor<length)addQuad(walls,wallIndices,point(cursor,wb),point(length,wb),point(length,wt),point(cursor,wt))}}
  group.add(mesh(walls,wallIndices,wall),mesh(windows,windowIndices,glass));const outline:number[]=[];for(let i=0;i<xy.length;i++){const a=xy[i],b=xy[(i+1)%xy.length];outline.push(a.x,a.y,minZ,b.x,b.y,minZ,a.x,a.y,minZ+height,b.x,b.y,minZ+height,a.x,a.y,minZ,a.x,a.y,minZ+height)}const outlineGeometry=new LineSegmentsGeometry();outlineGeometry.setPositions(outline);group.add(new LineSegments2(outlineGeometry,line));setBuildingId(group,id);return group;
}

function parseObjects(text:string){const objects=new Map<string,Point3[]>();let name="";for(const raw of text.split(/\r?\n/)){const line=raw.trim();if(line.startsWith("o ")){name=line.slice(2).trim();if(!objects.has(name))objects.set(name,[]);continue}if(line.startsWith("v ")&&name){const value=line.slice(2).trim().split(/\s+/).map(Number) as Point3;if(value.every(Number.isFinite))objects.get(name)!.push(value)}}return objects}

export function ObjViewer({url,buildings,selectedId,onSelectBuilding,showRoofPv=false}:{url?:string;buildings:Building[];selectedId?:string|null;onSelectBuilding:(id:string)=>void;showRoofPv?:boolean}){
  const host=useRef<HTMLDivElement>(null),groups=useRef(new Map<string,SelectableGroup>()),selectedRef=useRef(selectedId),showPvRef=useRef(showRoofPv),onSelectRef=useRef(onSelectBuilding);const [error,setError]=useState("");selectedRef.current=selectedId;showPvRef.current=showRoofPv;onSelectRef.current=onSelectBuilding;
  useEffect(()=>{for(const [id,group] of groups.current){const active=id===selectedId;group.userData.line.linewidth=active?3:1.15;group.userData.line.opacity=active?.9:.62;group.userData.pv.visible=showRoofPv&&active;group.renderOrder=active?2:0}},[selectedId,showRoofPv]);
  useEffect(()=>{if(!host.current||!url)return;let disposed=false;const container=host.current,scene=new THREE.Scene();scene.background=new THREE.Color(0xf3f6f5);setError("");const camera=createIsometricCamera(),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(container.clientWidth,container.clientHeight);container.replaceChildren(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x64736f,2.3));const key=new THREE.DirectionalLight(0xffffff,2.5);key.position.set(2,4,3);scene.add(key);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;let modelSpan=20;
    const campus=new THREE.Group(),raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let down={x:0,y:0};const pointerDown=(event:PointerEvent)=>{down={x:event.clientX,y:event.clientY}};const pick=(event:PointerEvent)=>{if(Math.hypot(event.clientX-down.x,event.clientY-down.y)>5)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects([...groups.current.values()],true).find(item=>item.object.userData.buildingId),id=hit?.object.userData.buildingId;if(id)onSelectRef.current(id)};renderer.domElement.addEventListener("pointerdown",pointerDown);renderer.domElement.addEventListener("pointerup",pick);
    fetch(url).then(response=>{if(!response.ok)throw new Error(`HTTP ${response.status}`);return response.text()}).then(text=>{if(disposed)return;const objects=parseObjects(text),next=new Map<string,SelectableGroup>();for(const building of buildings){const vertices=objects.get(building.id);if(!vertices?.length)continue;const model=buildingModel(building.id,vertices,building);if(model){next.set(building.id,model);campus.add(model)}}groups.current=next;const boundary=objects.get(`${buildings[0]?.campusId}_campus_boundary`);if(boundary&&boundary.length>2){const geometry=new THREE.BufferGeometry().setFromPoints(boundary.map(v=>new THREE.Vector3(v[0],v[1],v[2])));campus.add(new THREE.LineLoop(geometry,new THREE.LineBasicMaterial({color:0x7ea99d,transparent:true,opacity:.65})))}for(const [id,group] of next){const active=id===selectedRef.current;group.userData.line.linewidth=active?3:1.15;group.userData.line.opacity=active?.9:.62;group.userData.pv.visible=showPvRef.current&&active}campus.rotation.x=-Math.PI/2;campus.updateMatrixWorld(true);const box=new THREE.Box3();for(const group of next.values())box.expandByObject(group);if(box.isEmpty())box.setFromObject(campus);const center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3());campus.position.sub(center);scene.add(campus);modelSpan=Math.max(size.x,size.y,size.z,20);fitIsometricCamera(camera,container,modelSpan);controls.target.set(0,0,0);controls.update()}).catch(reason=>{if(!disposed)setError(`Campus OBJ could not be loaded: ${String(reason)}`)});
    let frame=0,resizeFrame=0;const animate=()=>{controls.update();renderer.render(scene,camera);frame=requestAnimationFrame(animate)};animate();const observer=new ResizeObserver(()=>{cancelAnimationFrame(resizeFrame);resizeFrame=requestAnimationFrame(()=>{if(!container.clientWidth)return;fitIsometricCamera(camera,container,modelSpan);renderer.setSize(container.clientWidth,container.clientHeight)})});observer.observe(container);
    return()=>{disposed=true;cancelAnimationFrame(frame);cancelAnimationFrame(resizeFrame);observer.disconnect();controls.dispose();renderer.domElement.removeEventListener("pointerdown",pointerDown);renderer.domElement.removeEventListener("pointerup",pick);campus.traverse(item=>{if(item instanceof THREE.Mesh||item instanceof THREE.Line||item instanceof THREE.LineSegments){item.geometry?.dispose();const materials=Array.isArray(item.material)?item.material:[item.material];materials.forEach(material=>{if(material instanceof THREE.MeshStandardMaterial)material.map?.dispose();material?.dispose()})}});groups.current.clear();renderer.dispose();renderer.forceContextLoss();container.replaceChildren()};
  },[url,buildings]);
  const selected=buildings.find(item=>item.id===selectedId),prediction=selected?.prediction;
  return <div className="obj-viewer campus-obj-viewer"><div className="viewer-canvas-host" ref={host}/><div className="campus-viewer-hint">Click a building in the 3D campus model</div>{selected&&<div className="campus-selection-card"><span>Selected building</span><b>{`Building ${selected.campusBuildingNo}`}</b><small>{selected.teachingId}</small>{prediction&&<div><em>EUI <strong>{prediction.annualEui.toFixed(2)}</strong></em><em>Epv <strong>{prediction.annualEpv.toFixed(0)}</strong></em><em>CEI <strong>{prediction.annualCei.toFixed(2)}</strong></em></div>}</div>}{error&&<div className="viewer-error">{error}</div>}</div>;
}
